"""Environment sealing, the second stage of ProdPush.

Scope is Phase 6 module 6.2. Section 7 stage 2 states it: read the local .env,
flag real secrets and placeholders, generate .env.production with confirmed
values, verify .env.example covers all keys, and confirm .env.production is
gitignored, with no secrets ever written to any committed file.

This module reads and writes environment files. It builds no image and calls no
deployment API. Those are 6.3 and 6.5.

Nothing here invents a second secret detector
---------------------------------------------
Classification is module 2.3's, called through its own primitives. is_placeholder
carries the placeholder patterns, prefix_hit carries the known provider
prefixes, and shannon with BASE64_LIMIT, HEX_LIMIT and MARGIN carries the
entropy thresholds that were measured against real code. The order the checks
run in here is the order entropy.scan_text runs them in, for the same reasons.

scan_text itself cannot be called directly on a .env file. It scans a line for
runs of at least twenty characters, and in KEY=VALUE form the key, the equals
sign and the value are one run, so a hit would report the key name as part of
the credential. Sealing needs a verdict per key, so the file is parsed into
pairs here and each value is classified with the same primitives. Parsing an env
file is not secret detection, and no threshold or pattern is restated.

Nothing here re-implements key coverage either
-----------------------------------------------
The .env.example check is module 2.2's ENV-001 logic, called through the same
two functions that rule uses: env_keys reads what the code actually references
from the parsed syntax trees, and declared_keys reads what the template
declares. This module compares those two sets exactly as env_coverage does.

Why the gitignore condition is a hard failure
----------------------------------------------
Section 2.1 design principle 5 says secrets are never written to any committed
file, and .env.production holds the confirmed real values. So the check runs
before anything is written, and a project that does not ignore the file gets no
file written at all. Warning and writing anyway would leave a live credential in
a working tree one git add away from being committed, which is the exact
outcome the principle exists to prevent.

git check-ignore decides it, because it is the only thing that reads nested
ignore files, negations and the global excludes the way git itself will. When
git cannot answer, the check fails rather than guessing.

Placeholders are never written through
---------------------------------------
A value flagged as a stand-in is reported for the developer to supply and is
left out of the generated file. Passing it through would ship a service
configured with the word CHANGEME, which fails at run time in a way that is
harder to diagnose than a missing key.
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from prodpilot import astchecks, entropy

logger = logging.getLogger(__name__)

ENV = ".env"
EXAMPLE = ".env.example"
PRODUCTION = ".env.production"

# The header written at the top of the generated file, so anyone who opens it
# knows what it is and that it must not be committed.
HEADER = (
    "# Generated by ProdPilot. Real values, never commit this file.\n"
    "# Regenerate it rather than editing it by hand.\n"
)


class Kind(str, Enum):
    """What one environment value turned out to be."""

    SECRET = "secret"
    PLAIN = "plain"
    PLACEHOLDER = "placeholder"
    UNSURE = "unsure"


class SealError(Exception):
    """Raised when sealing cannot proceed safely."""


@dataclass(frozen=True)
class Value:
    """One key from the local .env, and what its value looks like.

    The raw value is held so the file can be written, and never leaves this
    object through to_dict, which masks it the way module 2.3 masks a finding.
    """

    key: str
    raw: str
    kind: Kind
    reason: str

    @property
    def real(self) -> bool:
        """Whether this value may be written to the sealed file."""
        return self.kind in (Kind.SECRET, Kind.PLAIN)

    @property
    def masked(self) -> str:
        if self.kind is not Kind.SECRET:
            return self.raw
        if len(self.raw) <= 12:
            return self.raw[:2] + "..." + self.raw[-2:]
        return self.raw[:6] + "..." + self.raw[-4:]

    def to_dict(self) -> dict[str, object]:
        return {
            "key": self.key,
            "kind": self.kind.value,
            "reason": self.reason,
            "value": self.masked,
        }


@dataclass(frozen=True)
class Seal:
    """The result stage 3 and later stages consume."""

    project: str
    values: tuple[Value, ...] = field(default_factory=tuple)
    uncovered: tuple[str, ...] = field(default_factory=tuple)
    ignored: bool = False
    written: str = ""
    reason: str = ""

    @property
    def sealed(self) -> tuple[str, ...]:
        """Keys written to the sealed file."""
        return tuple(v.key for v in self.values if v.real)

    @property
    def blocked(self) -> tuple[str, ...]:
        """Keys the developer has to supply before deployment can proceed."""
        return tuple(v.key for v in self.values
                     if v.kind in (Kind.PLACEHOLDER, Kind.UNSURE))

    @property
    def ok(self) -> bool:
        """Whether stage 3 may proceed.

        Everything has to hold: the file was written, the ignore rule covers it,
        no key is waiting on the developer, and the template covers the code.
        """
        return bool(self.written) and self.ignored and not self.blocked and not self.uncovered

    def to_dict(self) -> dict[str, object]:
        return {
            "project": self.project,
            "ok": self.ok,
            "reason": self.reason,
            "ignored": self.ignored,
            "written": self.written,
            "sealed": list(self.sealed),
            "blocked": list(self.blocked),
            "uncovered": list(self.uncovered),
            "values": [v.to_dict() for v in self.values],
        }

    def summary(self) -> str:
        if self.ok:
            return f"{self.project}: sealed {len(self.sealed)} key(s) into {PRODUCTION}"
        return f"{self.project}: not sealed, {self.reason}"


def pairs(text: str) -> dict[str, str]:
    """Key and value for every assignment in an env file.

    Follows the same reading module 2.2's declared_keys uses: blank lines and
    comments are skipped, and a line splits on its first equals sign. Surrounding
    quotes are stripped because a shell would strip them too, and a quoted secret
    is still a secret.
    """
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        out[key] = value
    return out


def stand_in(value: str) -> bool:
    """Whether a value is an explicit placeholder, at any length.

    Module 2.3's PLACEHOLDERS pattern carries the wording, and the angle
    bracket form is the one shape that pattern does not cover.
    """
    stripped = value.strip("\"'`").strip()
    if entropy.PLACEHOLDERS.match(stripped):
        return True
    return stripped.startswith("<") and stripped.endswith(">")


def classify(value: str) -> tuple[Kind, str]:
    """What one value is, decided by module 2.3's own primitives.

    The order matches entropy.scan_text with one addition, the length gate,
    which exists because this module calls is_placeholder on input scan_text
    never gives it.

    entropy.RUN_RE only ever hands is_placeholder a run of MIN_LEN characters or
    more, and one of that function's rules treats two or fewer distinct
    characters as a stand-in, which is right for xxxxxxxxxxxxxxxxxxxx and wrong
    for a port number. An env file holds values of every length, so anything
    shorter than MIN_LEN is not credential shaped by module 2.3's own threshold
    and is read as ordinary configuration unless it says outright that it is a
    placeholder. A known provider prefix still decides first, since that is
    definitive whatever the length.
    """
    if not value:
        return Kind.PLACEHOLDER, "the value is empty"
    if stand_in(value):
        return Kind.PLACEHOLDER, "the value looks like a stand-in, not a real credential"

    label = entropy.prefix_hit(value)
    if label:
        return Kind.SECRET, f"matches a known {label}"

    if len(value) < entropy.MIN_LEN:
        return Kind.PLAIN, "too short to be a credential, read as configuration"

    if entropy.is_placeholder(value):
        return Kind.PLACEHOLDER, "the value looks like a stand-in, not a real credential"

    base64 = entropy.shannon(value, entropy.BASE64_CHARS) if set(value) & entropy.BASE64_CHARS else 0.0
    hexed = entropy.shannon(value, entropy.HEX_CHARS) if set(value) <= entropy.HEX_CHARS else 0.0

    if base64 >= entropy.BASE64_LIMIT or hexed >= entropy.HEX_LIMIT:
        return Kind.SECRET, f"high entropy value, {max(base64, hexed):.2f}"
    near = (entropy.BASE64_LIMIT - entropy.MARGIN <= base64 < entropy.BASE64_LIMIT
            or entropy.HEX_LIMIT - entropy.MARGIN <= hexed < entropy.HEX_LIMIT)
    if near:
        return Kind.UNSURE, f"borderline entropy, {max(base64, hexed):.2f}, needs confirming"
    return Kind.PLAIN, "an ordinary configuration value"


def uncovered(root: Path) -> tuple[str, ...]:
    """Keys the code reads that .env.example does not declare.

    Module 2.2's ENV-001 comparison, run through the same two functions that
    rule uses rather than a second reading of either side.
    """
    try:
        src = astchecks.load_sources(root)
    except (OSError, NotADirectoryError) as exc:
        raise SealError(f"cannot read the project source: {exc}") from exc

    used: set[str] = set()
    for _, tree in src.ok_trees():
        used |= astchecks.env_keys(tree)
    if not used:
        return ()
    declared = astchecks.declared_keys(src.env_example)
    return tuple(sorted(key for key in used if key not in declared))


def ignored(root: Path, name: str = PRODUCTION) -> bool:
    """Whether the project's ignore rules cover a file.

    Asks git, which is the only thing that reads nested ignore files, negations
    and global excludes the way git itself will when the developer runs git add.
    Anything git cannot answer is treated as not ignored, so the caller fails
    closed rather than writing a secret into a tracked tree.
    """
    try:
        done = subprocess.run(
            ("git", "check-ignore", "-q", name),
            cwd=str(root),
            capture_output=True,
            timeout=15,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        logger.warning("cannot ask git whether %s is ignored: %s", name, exc)
        return False
    # 0 means ignored, 1 means not ignored, anything else is an error.
    return done.returncode == 0


def render(values: tuple[Value, ...]) -> str:
    """The sealed file's contents, real values only."""
    lines = [HEADER]
    for value in values:
        if value.real:
            lines.append(f"{value.key}={value.raw}\n")
    return "".join(lines)


def run(root: str | Path) -> Seal:
    """Seal a project's environment for deployment.

    Never raises for a project that cannot be sealed. Stage 3 acts on the
    result, so a missing file or an unignored target is a reported failure
    rather than an exception.
    """
    base = Path(root)
    name = base.name or str(base)

    if not base.is_dir():
        return Seal(project=name, reason=f"{base} is not a project directory")

    source = base / ENV
    if not source.is_file():
        return Seal(project=name, reason=f"there is no {ENV} to seal")

    try:
        text = source.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return Seal(project=name, reason=f"cannot read {ENV}: {exc}")

    found = pairs(text)
    if not found:
        return Seal(project=name, reason=f"{ENV} declares no values")

    values = tuple(Value(key, raw, *classify(raw)) for key, raw in found.items())

    try:
        missing = uncovered(base)
    except SealError as exc:
        return Seal(project=name, values=values, reason=str(exc))

    # Checked before anything is written. A project that does not ignore the
    # target gets no file, because writing one would put real values in a
    # tracked tree.
    covered = ignored(base)
    if not covered:
        logger.warning("%s is not ignored in %s, refusing to write it", PRODUCTION, base)
        return Seal(
            project=name,
            values=values,
            uncovered=missing,
            ignored=False,
            reason=f"{PRODUCTION} is not covered by .gitignore, so it was not written",
        )

    waiting = tuple(v.key for v in values if v.kind in (Kind.PLACEHOLDER, Kind.UNSURE))
    if waiting:
        return Seal(
            project=name,
            values=values,
            uncovered=missing,
            ignored=True,
            reason=f"{len(waiting)} value(s) need the developer: {', '.join(waiting)}",
        )

    target = base / PRODUCTION
    try:
        target.write_text(render(values), encoding="utf-8")
    except OSError as exc:
        return Seal(project=name, values=values, uncovered=missing, ignored=True,
                    reason=f"cannot write {PRODUCTION}: {exc}")

    result = Seal(
        project=name,
        values=values,
        uncovered=missing,
        ignored=True,
        written=str(target),
        reason="" if not missing else
        f"{len(missing)} key(s) read by the code are missing from {EXAMPLE}",
    )
    logger.info("%s", result.summary())
    return result
